// Commercial Bus Chassis & Coachbuilder Engineering Master
export interface BusChassisSpecification {
  modelId: string;
  chassisManufacturer: string;
  coachBuilder: string;
  commercialName: string;
  overallLengthMm: number;
  overallWidthMm: number;
  overallHeightMm: number;
  wheelbaseMm: number;
  grossVehicleWeightKg: number;
  engineModel: string;
  displacementCc: number;
  maxPowerHp: number;
  maxTorqueNm: number;
  transmissionType: 'MANUAL_6_SPEED' | 'AUTOMATED_I_SHIFT_12_SPEED' | 'VOITH_AUTOMATIC_6_SPEED' | 'ZF_AS_TRONIC';
  suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION' | 'PARABOLIC_LEAF_AIR_COMBO';
  retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER' | 'TELMA_ELECTROMAGNETIC' | 'VOLVO_VEB_ENGINE_BRAKE';
  fuelTankCapacityLitres: number;
  adBlueDefTankCapacityLitres: number;
  ais052BusCodeComplianceCertificate: string;
}

export const BUS_CHASSIS_CATALOG: BusChassisSpecification[] = [
  {
    modelId: 'CH-VOL-9600-15M-V01',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #1',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV01'
  },
  {
    modelId: 'CH-VOL-9600-15M-V02',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #2',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV02'
  },
  {
    modelId: 'CH-VOL-9600-15M-V03',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #3',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV03'
  },
  {
    modelId: 'CH-VOL-9600-15M-V04',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #4',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV04'
  },
  {
    modelId: 'CH-VOL-9600-15M-V05',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #5',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV05'
  },
  {
    modelId: 'CH-VOL-9600-15M-V06',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #6',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV06'
  },
  {
    modelId: 'CH-VOL-9600-15M-V07',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #7',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV07'
  },
  {
    modelId: 'CH-VOL-9600-15M-V08',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #8',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV08'
  },
  {
    modelId: 'CH-VOL-9600-15M-V09',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #9',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV09'
  },
  {
    modelId: 'CH-VOL-9600-15M-V10',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #10',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV10'
  },
  {
    modelId: 'CH-VOL-9600-15M-V11',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #11',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV11'
  },
  {
    modelId: 'CH-VOL-9600-15M-V12',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #12',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV12'
  },
  {
    modelId: 'CH-VOL-9600-15M-V13',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #13',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV13'
  },
  {
    modelId: 'CH-VOL-9600-15M-V14',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #14',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV14'
  },
  {
    modelId: 'CH-VOL-9600-15M-V15',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #15',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV15'
  },
  {
    modelId: 'CH-VOL-9600-15M-V16',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #16',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV16'
  },
  {
    modelId: 'CH-VOL-9600-15M-V17',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #17',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV17'
  },
  {
    modelId: 'CH-VOL-9600-15M-V18',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #18',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV18'
  },
  {
    modelId: 'CH-VOL-9600-15M-V19',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #19',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV19'
  },
  {
    modelId: 'CH-VOL-9600-15M-V20',
    chassisManufacturer: 'Volvo Buses India',
    coachBuilder: 'Volvo Hosakote Coach Plant',
    commercialName: 'Volvo 9600 15m Multi-Axle Sleeper Series #20',
    overallLengthMm: 15000,
    overallWidthMm: 2600,
    overallHeightMm: 3950,
    wheelbaseMm: 8350,
    grossVehicleWeightKg: 22200,
    engineModel: 'Volvo D8K Euro VI Step E',
    displacementCc: 7700,
    maxPowerHp: 350,
    maxTorqueNm: 1450,
    transmissionType: 'AUTOMATED_I_SHIFT_12_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOLVO_VEB_ENGINE_BRAKE',
    fuelTankCapacityLitres: 540,
    adBlueDefTankCapacityLitres: 60,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-VOL-9600-REV20'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V01',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #1',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV01'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V02',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #2',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV02'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V03',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #3',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV03'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V04',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #4',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV04'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V05',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #5',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV05'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V06',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #6',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV06'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V07',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #7',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV07'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V08',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #8',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV08'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V09',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #9',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV09'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V10',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #10',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV10'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V11',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #11',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV11'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V12',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #12',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV12'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V13',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #13',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV13'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V14',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #14',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV14'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V15',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #15',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV15'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V16',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #16',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV16'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V17',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #17',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV17'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V18',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #18',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV18'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V19',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #19',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV19'
  },
  {
    modelId: 'CH-SCA-METRO-14M-V20',
    chassisManufacturer: 'Scania Commercial Vehicles',
    coachBuilder: 'Scania Narasapura Coachworks',
    commercialName: 'Scania Metrolink HD 14.5m Series #20',
    overallLengthMm: 14500,
    overallWidthMm: 2600,
    overallHeightMm: 3850,
    wheelbaseMm: 7850,
    grossVehicleWeightKg: 21000,
    engineModel: 'Scania DC13 115 Euro VI',
    displacementCc: 12700,
    maxPowerHp: 410,
    maxTorqueNm: 2000,
    transmissionType: 'ZF_AS_TRONIC',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 500,
    adBlueDefTankCapacityLitres: 50,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-SCA-145-REV20'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V01',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #1',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV01'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V02',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #2',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV02'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V03',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #3',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV03'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V04',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #4',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV04'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V05',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #5',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV05'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V06',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #6',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV06'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V07',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #7',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV07'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V08',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #8',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV08'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V09',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #9',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV09'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V10',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #10',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV10'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V11',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #11',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV11'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V12',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #12',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV12'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V13',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #13',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV13'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V14',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #14',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV14'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V15',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #15',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV15'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V16',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #16',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV16'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V17',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #17',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV17'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V18',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #18',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV18'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V19',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #19',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV19'
  },
  {
    modelId: 'CH-MB-GLIDER-14M-V20',
    chassisManufacturer: 'Mercedes-Benz / Daimler',
    coachBuilder: 'BharatBenz Oragadam Plant',
    commercialName: 'Mercedes-Benz 2441 Super-High-Deck Series #20',
    overallLengthMm: 14000,
    overallWidthMm: 2600,
    overallHeightMm: 3900,
    wheelbaseMm: 7500,
    grossVehicleWeightKg: 20500,
    engineModel: 'OM 457 LA 6-Cylinder Turbo',
    displacementCc: 11967,
    maxPowerHp: 408,
    maxTorqueNm: 1900,
    transmissionType: 'VOITH_AUTOMATIC_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'VOITH_HYDRODYNAMIC_RETARDER',
    fuelTankCapacityLitres: 480,
    adBlueDefTankCapacityLitres: 55,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-MB-2441-REV20'
  },
  {
    modelId: 'CH-BB-1624-12M-V01',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #1',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV01'
  },
  {
    modelId: 'CH-BB-1624-12M-V02',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #2',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV02'
  },
  {
    modelId: 'CH-BB-1624-12M-V03',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #3',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV03'
  },
  {
    modelId: 'CH-BB-1624-12M-V04',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #4',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV04'
  },
  {
    modelId: 'CH-BB-1624-12M-V05',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #5',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV05'
  },
  {
    modelId: 'CH-BB-1624-12M-V06',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #6',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV06'
  },
  {
    modelId: 'CH-BB-1624-12M-V07',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #7',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV07'
  },
  {
    modelId: 'CH-BB-1624-12M-V08',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #8',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV08'
  },
  {
    modelId: 'CH-BB-1624-12M-V09',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #9',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV09'
  },
  {
    modelId: 'CH-BB-1624-12M-V10',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #10',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV10'
  },
  {
    modelId: 'CH-BB-1624-12M-V11',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #11',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV11'
  },
  {
    modelId: 'CH-BB-1624-12M-V12',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #12',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV12'
  },
  {
    modelId: 'CH-BB-1624-12M-V13',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #13',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV13'
  },
  {
    modelId: 'CH-BB-1624-12M-V14',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #14',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV14'
  },
  {
    modelId: 'CH-BB-1624-12M-V15',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #15',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV15'
  },
  {
    modelId: 'CH-BB-1624-12M-V16',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #16',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV16'
  },
  {
    modelId: 'CH-BB-1624-12M-V17',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #17',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV17'
  },
  {
    modelId: 'CH-BB-1624-12M-V18',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #18',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV18'
  },
  {
    modelId: 'CH-BB-1624-12M-V19',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #19',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV19'
  },
  {
    modelId: 'CH-BB-1624-12M-V20',
    chassisManufacturer: 'BharatBenz Commercial Vehicles',
    coachBuilder: 'Prakash Coaches Bangalore',
    commercialName: 'BharatBenz 1624 Sleeper Coach Series #20',
    overallLengthMm: 12000,
    overallWidthMm: 2600,
    overallHeightMm: 3800,
    wheelbaseMm: 5950,
    grossVehicleWeightKg: 16200,
    engineModel: 'OM 926 6-Cylinder Diesel',
    displacementCc: 7200,
    maxPowerHp: 240,
    maxTorqueNm: 850,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 380,
    adBlueDefTankCapacityLitres: 40,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-BB-1624-REV20'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V01',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #1',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV01'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V02',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #2',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV02'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V03',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #3',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV03'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V04',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #4',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV04'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V05',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #5',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV05'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V06',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #6',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV06'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V07',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #7',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV07'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V08',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #8',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV08'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V09',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #9',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV09'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V10',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #10',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV10'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V11',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #11',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV11'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V12',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #12',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV12'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V13',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #13',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV13'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V14',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #14',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV14'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V15',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #15',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV15'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V16',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #16',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV16'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V17',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #17',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV17'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V18',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #18',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV18'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V19',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #19',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV19'
  },
  {
    modelId: 'CH-AL-GARUD-13M-V20',
    chassisManufacturer: 'Ashok Leyland Limited',
    coachBuilder: 'SM Kannappa / KMS Coachworks',
    commercialName: 'Ashok Leyland 13.5m Garud Coach Series #20',
    overallLengthMm: 13500,
    overallWidthMm: 2600,
    overallHeightMm: 3750,
    wheelbaseMm: 6600,
    grossVehicleWeightKg: 18500,
    engineModel: 'H-Series 6-Cylinder CRS i-Gen6',
    displacementCc: 5660,
    maxPowerHp: 250,
    maxTorqueNm: 900,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'FULL_ELECTRONIC_AIR_SUSPENSION',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 400,
    adBlueDefTankCapacityLitres: 45,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-AL-135-REV20'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V01',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #1',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV01'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V02',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #2',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV02'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V03',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #3',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV03'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V04',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #4',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV04'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V05',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #5',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV05'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V06',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #6',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV06'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V07',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #7',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV07'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V08',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #8',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV08'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V09',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #9',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV09'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V10',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #10',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV10'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V11',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #11',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV11'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V12',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #12',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV12'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V13',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #13',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV13'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V14',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #14',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV14'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V15',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #15',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV15'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V16',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #16',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV16'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V17',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #17',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV17'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V18',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #18',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV18'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V19',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #19',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV19'
  },
  {
    modelId: 'CH-TATA-MAGNA-12M-V20',
    chassisManufacturer: 'Tata Motors Commercial',
    coachBuilder: 'Automobile Corporation of Goa Ltd (ACGL)',
    commercialName: 'Tata LPO 1618 Magna Coach Series #20',
    overallLengthMm: 12000,
    overallWidthMm: 2550,
    overallHeightMm: 3700,
    wheelbaseMm: 5900,
    grossVehicleWeightKg: 16200,
    engineModel: 'Cummins ISBe 5.6L BS-VI',
    displacementCc: 5600,
    maxPowerHp: 180,
    maxTorqueNm: 700,
    transmissionType: 'MANUAL_6_SPEED',
    suspensionType: 'PARABOLIC_LEAF_AIR_COMBO',
    retarderBrakingSystem: 'TELMA_ELECTROMAGNETIC',
    fuelTankCapacityLitres: 350,
    adBlueDefTankCapacityLitres: 35,
    ais052BusCodeComplianceCertificate: 'ARAI-BUS-052-TAT-1618-REV20'
  },
];
